// <auto-generated />
namespace EPrescribing.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_tbl_FooterContent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tbl_FooterContent));
        
        string IMigrationMetadata.Id
        {
            get { return "202110140601245_add_tbl_FooterContent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
