// <auto-generated />
namespace EPrescribing.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class madicineid_remove_medicine_history : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madicineid_remove_medicine_history));
        
        string IMigrationMetadata.Id
        {
            get { return "202109281631477_madicineid_remove_medicine_history"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
