// <auto-generated />
namespace EPrescribing.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class diagonistictest_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(diagonistictest_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "202109281811230_diagonistictest_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
