// <auto-generated />
namespace EPrescribing.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class diseasename_trearmentname_required_remove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(diseasename_trearmentname_required_remove));
        
        string IMigrationMetadata.Id
        {
            get { return "202109281755386_diseasename_trearmentname_required_remove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
